const { GoogleSpreadsheet } = require("google-spreadsheet");
const creds = require("./creds.json");
const customCreds = require("./customCreds.json");
const twilio = require('twilio')

const event = {
  name: "JMAC",
  number: "6176945102",
  zipcode: "80211",
};

module.exports.handler = async (event) => {
  // This Lambda signs users up for weather alets
  const doc = new GoogleSpreadsheet(customCreds.googleSheetID);

  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: creds.client_email,
    private_key: creds.private_key,
  }); // loads document properties and worksheets
  await doc.loadInfo();
  const firstSheet = doc.sheetsByIndex[0];

  await firstSheet.addRow({
    name: event.name,
    number: event.number,
    zipcode: event.zipcode,
  });
};
module.exports.handler(event);
